### ISSUE TITLE
Windswept 1.18.2 compatibilities

### ISSUE THREAD

**Issue by mrdrip404** [rosevcook/windswept#1]
Chestnut dosen't spawn in world and compatibilities are not craftable. Blueprint and woodwork are up to date
![obraz_2022-11-04_174957015](https://user-images.githubusercontent.com/102256630/200031217-7045aa1e-dc72-427c-8e66-1bcd3364033a.png)
![obraz_2022-11-04_175030129](https://user-images.githubusercontent.com/102256630/200031326-127a5647-656c-43dc-88cb-60e27866e63e.png)

**Comment by rosevcook** [comment]
New features are only updated to the newest version of Minecraft. Windswept for 1.18.2 is version 1.0.0 whereas 1.19.2 is 2.0.0 with all the new features. Sorry for any misunderstanding.
