### ISSUE TITLE
Crash when loading new chunks 

### ISSUE THREAD

**Issue by thelegitdolt** [rosevcook/windswept#42]
not exactly sure what happened, this crash happened me three times at random intervals. It does happen very consistently though

https://gist.github.com/thelegitdolt/2a184c54fd70392b0842318db3bf002c < Latest Log
https://gist.github.com/thelegitdolt/535c74da75e532593ca01f3c026e1050 < Crash report

**Comment by thelegitdolt** [comment]
i'm pretty sure this is a duplicate of #14

**Comment by thelegitdolt** [comment]
and #21

**Comment by thelegitdolt** [comment]
but yea, i am using the latest version, as you can see at my crash report. so yea

**Comment by thelegitdolt** [comment]
on further inspection, i'm pretty sure this is caused by the Geophilics mod changing the birch tree feature.
I am not 100% sure on this and am currently unable to test anything.

**Comment by rosevcook** [comment]
huh i though i fixed that

**Comment by thelegitdolt** [comment]
i've been playing with a github build for the past two weeks, and have not gotten the crash again, so I think this might be safe to close

**Comment by thelegitdolt** [comment]
oh my god it's happening again

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/a0bd4718d987ce5420ad2ff2f926e229
