### ISSUE TITLE
Crashes when loading the game or a world

### ISSUE THREAD

**Issue by Icedteaman** [rosevcook/windswept#43]
[New Text Document.txt](https://github.com/rosevcook/windswept/files/10820146/New.Text.Document.txt)

**Comment by enduum** [comment]
A little more info, logs mention a ticking entity and SnowBootsItem on world load or generation. Seems to be a different entity each crash but it doesn't _always_ crash. Here's two crash reports:
[one involving a Passerine from Habitat](https://pastebin.com/2nUFYuBp),
and [one involving a vanilla horse](https://pastebin.com/XYqRD1yx).
