### ISSUE TITLE
Foliage of trees from your mod with graphics: Fast, does not match.

### ISSUE THREAD

**Issue by MrJorman** [rosevcook/windswept#56]
![image](https://user-images.githubusercontent.com/55187962/229393061-e1da8719-0004-4b0c-ac65-e9955763c23c.png)

Foliage of trees from your mod with graphics: Fast, does not match. The foliage is transparent, although it should be dense if the graphics setting is set to Fast.

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/229393188-8fc719ec-22c1-45d1-9877-c3c8f75545da.png)
![image](https://user-images.githubusercontent.com/55187962/229393193-41d0a39f-3514-4fd2-8f38-a4d8c12344e8.png)

**Comment by GitJhopa** [comment]
please fix.
