### ISSUE TITLE
Chestnut and Holly Wood Blocks Not Orienting Properly

### ISSUE THREAD

**Issue by TieDye4** [rosevcook/windswept#62]
The "Chestnut Wood" and "Holly Wood" blocks do not change their texture orientation based on the the block they're placed against like any other wood type.

**Comment by WaterOre** [comment]
Hey TieDye4!

Not a dev on this mod, but I've never known this to be a feature in any vanilla or modded woodset. Are you running any additional mods that add this ability? Windswept does include built-in support for Quark's vertical planks, so if you need the texture to align you could try using those.

**Comment by TieDye4** [comment]
Yes :)

**Comment by TieDye4** [comment]
My guess is it's just referencing the wrong base model, even a texture pack could fix it I imagine; Just bringing it up for consistency's sake.

**Comment by WaterOre** [comment]
Confirmed the issue with latest version of Windswept - Top structures built using logs, bottom structures built using wood. Each built in the same way. From left to right: Oak, Holly, Chestnut

![image](https://github.com/rosevcook/windswept/assets/46122502/6d52eb21-2230-4a49-9f72-4ad3b73d76b9)

**Comment by TieDye4** [comment]
It also affects it the rotational y-axis (from a top-down POV).
