### ISSUE TITLE
[1.19.2, v2.0.2] Wild Berries are not included in Farmer's Delight and Berry Good recipes

### ISSUE THREAD

**Issue by Mikzoru** [rosevcook/windswept#7]
Unsure if this is intended or not. I was expecting to be able to use wild berries in recipes such as meatballs from Berry Good or fruit salad from Farmer's Delight, but they do not count as valid substitutes for sweet berries.
On the offchance that this is intended, I apologize for the confusion, and hope you would not mind me adding wild berries to these recipes and more via CraftTweaker in modpacks.

**Comment by rosevcook** [comment]
wild berried are not a substitution for meatballs from berry good but they should be in farmers delight fruit salad. ill fix this in the next update.
