### ISSUE TITLE
Can Windswept be used in modpacks?

### ISSUE THREAD

**Issue by Trobador** [rosevcook/windswept#75]
Hello, thank you for your work on Windswept.

I am working on a modpack, planned to be published on Modrinth. I would like to include Windswept, but I'm unable to find any information on permissions regarding modpack usage. The only given license information is "all rights reserved" and no documentation I can find on here mentions modpacks. Besides, in my case, since Windswept is not hosted on Modrinth, if allowed, I may need to redistribute the relevant build of Windswept within the modpack, which complicates things further.

Would it be possible to get a clarification regarding this and possibly to add it to the Curseforge page or GitHub README? Thanks in advance.

**Comment by rosevcook** [comment]
you can include it in your modrinth modpack once i put windswept on modrinth. which i will do when i have the time.
