### ISSUE TITLE
Suggestion for farmer's delight and mutton pie

### ISSUE THREAD

**Issue by IlTAKlI** [rosevcook/windswept#8]
Is it possible to make it so if you have farmer's delight installed alongside windswept that the mutton pie will follow the rules of the farmer's delight pies?

Farmer's delight pies use a different recipe using pie crust and they're placeable and can be sliced

**Comment by rosevcook** [comment]
Other pies in the game don't follow the rules of FD's pies such as pumpkin pies. I don't think mutton pie should follow this rule also because of how abundant it is, they can be found very easily in taiga village chests so if they were placeable and sliceable they would be very OP.
